// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIBZfFyY5VlAmGgo_uafDeb29mjVJrl38',
    appId: '1:1053454951256:web:7633986253e64d5ce3bb2d',
    messagingSenderId: '1053454951256',
    projectId: 'learningprogress-307a5',
    authDomain: 'learningprogress-307a5.firebaseapp.com',
    storageBucket: 'learningprogress-307a5.firebasestorage.app',
    measurementId: 'G-TVRP0SYPVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9fH6bqEmwSDSUBDJx_REmyxOIoI14GZY',
    appId: '1:1053454951256:android:9db224be66eeb0fee3bb2d',
    messagingSenderId: '1053454951256',
    projectId: 'learningprogress-307a5',
    storageBucket: 'learningprogress-307a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAMyh103w_uaksOZz6c-BO2V5f5-s4x4o',
    appId: '1:1053454951256:ios:7f701f074bced6c6e3bb2d',
    messagingSenderId: '1053454951256',
    projectId: 'learningprogress-307a5',
    storageBucket: 'learningprogress-307a5.firebasestorage.app',
    iosBundleId: 'com.example.learningprogress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAMyh103w_uaksOZz6c-BO2V5f5-s4x4o',
    appId: '1:1053454951256:ios:7f701f074bced6c6e3bb2d',
    messagingSenderId: '1053454951256',
    projectId: 'learningprogress-307a5',
    storageBucket: 'learningprogress-307a5.firebasestorage.app',
    iosBundleId: 'com.example.learningprogress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIBZfFyY5VlAmGgo_uafDeb29mjVJrl38',
    appId: '1:1053454951256:web:e3f2534767aa2d0ce3bb2d',
    messagingSenderId: '1053454951256',
    projectId: 'learningprogress-307a5',
    authDomain: 'learningprogress-307a5.firebaseapp.com',
    storageBucket: 'learningprogress-307a5.firebasestorage.app',
    measurementId: 'G-N0PW6TKT0R',
  );
}
